#!/usr/bin/env python

import os
import time
import datetime
import feedparser
import sqlite3

import config
CONFIG = config.CONFIG()
with open(CONFIG.template, 'r') as f:
    CONFIG.template = f.read()

###############################################################################

def html_escape(data):
    # More thorough version than the one the builtin cgi module uses
    data = data.replace('&', '&amp;')
    data = data.replace('<', '&lt;')
    data = data.replace('>', '&gt;')
    data = data.replace('"', '&quot;')
    data = data.replace('\'', '&#39;') # Why doesn't the cgi module escape this one..?
    return data

def debug(text):
    if CONFIG.debug == True:
        print(text)

def sort_keys(dic):
    return sorted(dic.keys())

class news_generator():
    def __init__(self, db_file, max_items, feeds):
        self.today = int(time.time())
        self.max_items = max_items
        self.feeds = feeds
        con = sqlite3.connect(db_file)
        con.row_factory = sqlite3.Row
        cur = con.cursor()
        cur.execute('create table if not exists records (id integer primary key, title text, link text unique, timestamp integer, category text);')
        self.con = con
        self.cur = cur

    def close(self):
        self.con.close()

    def news(self):
        # shortcut func
        self.download()
        tmp =  self.prepare()
        self.close()
        return tmp

    def download(self):
        # parse all rss feeds and insert the news items into the database,
        # making sure the items are all unique inside the db
        debug('Downloading feeds...')
        for cat in sort_keys(self.feeds):
            debug('Category: %s' % cat)
            for feedlink in self.feeds[cat]:
                feeddata = feedparser.parse(feedlink)
                items = min(self.max_items, len(feeddata.entries))
                for i in range(items):
                    item = feeddata.entries[i]
                    title = html_escape(item['title'])
                    link = item['link']
                    values = (title, link, self.today, cat)
                    self.cur.execute('insert or ignore into records (title, link, timestamp, category) values(?, ?, ?, ?);', values)
                debug('Storing %i items from: %s' % (items, feedlink))
                self.con.commit()

    def prepare(self):
        # pull out all the news items again and prepare them for output
        debug('Preparing data...')
        data = ''
        for cat in sort_keys(self.feeds):
            data = '%s\n<h1>%s</h1><ol>\n' % (data, cat)
            values = (self.today, cat)
            self.cur.execute('select * from records where timestamp = ? and category = ?;', values)
            items = self.cur.fetchall()
            for item in items:
                tmp = '<li><a href="%s">%s</a></li>\n' % (item['link'], item['title'])
                data += tmp
            data += '</ol>'
        return data

###############################################################################

def main():
    # grab news from the feeds
    gen = news_generator(CONFIG.database_file, CONFIG.max_items, CONFIG.feeds)
    todays_news = gen.news()

    # prepare the html page
    template = CONFIG.template
    today = datetime.date.today()
    delta = datetime.timedelta(days=1)
    filename = os.path.join(CONFIG.output_dir, '%s.html' % str(today))
    parts = {
        'date': str(today),
        'next': '%s.html' % str(today + delta),
        'prev': '%s.html' % str(today - delta),
        'filename': CONFIG.latest_file,
        'feeds': todays_news,
    }

    # store the page
    with open(filename, 'w') as f:
        data = template % parts
        data = data.encode('utf-8')
        f.write(data)

    # try remove old symlink and make a new one pointing to today's page
    tmp = os.path.join(CONFIG.output_dir, CONFIG.latest_file)
    try:
        os.remove(tmp)
    except OSError:
        pass
    os.symlink(filename, tmp)

if __name__ == '__main__':
    main()

